// Vocabulary Themen, part three: body, clothes, work, education, free time.

const GESUNDHEIT = {
  intro:
    "Beim Arzt ist eine klassische Rollenspiel-Situation und ein häufiges Hören-Thema (Termin absagen, Anweisung der Sprechstundenhilfe). Wichtig: die Körperteile, die Schmerz-Konstruktionen und die Sätze zum Terminvereinbaren.",
  phrasesTitle: "Redemittel — beim Arzt",
  words: [
    ["der Körper", "body"],
    ["der Kopf", "head"],
    ["das Haar, die Haare", "hair"],
    ["das Auge, die Augen", "eye(s)"],
    ["das Ohr, die Ohren", "ear(s)"],
    ["die Nase", "nose"],
    ["der Mund", "mouth"],
    ["der Zahn, die Zähne", "tooth, teeth"],
    ["der Hals", "neck, throat"],
    ["der Rücken", "back"],
    ["der Bauch", "stomach, belly"],
    ["der Arm, die Arme", "arm(s)"],
    ["die Hand, die Hände", "hand(s)"],
    ["der Finger", "finger"],
    ["das Bein, die Beine", "leg(s)"],
    ["der Fuß, die Füße", "foot, feet"],
    ["das Knie", "knee"],
    ["das Herz", "heart"],
    ["krank / gesund", "ill / healthy"],
    ["die Krankheit", "illness"],
    ["die Erkältung", "cold"],
    ["die Grippe", "flu"],
    ["das Fieber", "fever"],
    ["der Husten", "cough"],
    ["der Schnupfen", "runny nose"],
    ["die Schmerzen (Pl.)", "pain", "Kopfschmerzen, Bauchschmerzen …"],
    ["wehtun", "to hurt", "Mein Kopf tut weh."],
    ["sich verletzen", "to injure oneself"],
    ["der Arzt / die Ärztin", "doctor"],
    ["die Praxis", "doctor's surgery", "AT: die Ordination"],
    ["das Krankenhaus", "hospital", "AT: das Spital"],
    ["der Termin", "appointment"],
    ["die Sprechstunde", "consultation hours"],
    ["die Versichertenkarte", "insurance card", "AT: die e-card"],
    ["untersuchen", "to examine"],
    ["das Rezept", "prescription"],
    ["die Tablette", "tablet"],
    ["die Medizin / das Medikament", "medicine"],
    ["die Apotheke", "pharmacy"],
    ["sich ausruhen", "to rest"],
    ["die Krankmeldung", "sick note"],
    ["gute Besserung!", "get well soon!"],
  ],
  phrases: [
    ["Ich möchte einen Termin vereinbaren.", "I'd like to make an appointment."],
    ["Ich fühle mich nicht gut.", "I don't feel well. — reflexiv: sich fühlen"],
    ["Ich habe seit gestern Halsschmerzen.", "I've had a sore throat since yesterday. — seit + Dativ, Präsens"],
    ["Mein Rücken tut weh.", "My back hurts. — wehtun, trennbar"],
    ["Wo haben Sie Schmerzen?", "Where does it hurt? — what the doctor asks"],
    ["Ich bin gegen Penizillin allergisch.", "I'm allergic to penicillin."],
    ["Nehmen Sie die Tabletten dreimal täglich.", "Take the tablets three times a day."],
    ["Ich muss den Termin leider absagen.", "Unfortunately I have to cancel the appointment."],
    ["Gute Besserung!", "Get well soon!"],
  ],
};

const KLEIDUNG = {
  intro:
    "Kleidung kombiniert Wortschatz mit Adjektivendungen und Farben — eine rote Jacke, ein blaues Hemd. Im Sprechen-Teil kommt sie in der Einkaufssituation vor, im Lesen als Online-Anzeige.",
  phrasesTitle: "Redemittel — Kleidung kaufen",
  words: [
    ["die Kleidung", "clothing"],
    ["das Hemd", "shirt"],
    ["die Bluse", "blouse"],
    ["das T-Shirt", "T-shirt"],
    ["der Pullover", "jumper", "kurz: der Pulli"],
    ["die Jacke", "jacket"],
    ["der Mantel", "coat"],
    ["die Hose", "trousers", "Singular im Deutschen!"],
    ["die Jeans", "jeans"],
    ["der Rock", "skirt"],
    ["das Kleid", "dress"],
    ["der Anzug", "suit"],
    ["die Socken (Pl.)", "socks"],
    ["die Schuhe (Pl.)", "shoes"],
    ["die Stiefel (Pl.)", "boots"],
    ["der Hut", "hat"],
    ["die Mütze", "beanie, cap"],
    ["der Schal", "scarf"],
    ["die Handschuhe (Pl.)", "gloves"],
    ["der Gürtel", "belt"],
    ["die Tasche", "bag"],
    ["die Brille", "glasses", "Singular im Deutschen!"],
    ["rot", "red"],
    ["blau", "blue"],
    ["grün", "green"],
    ["gelb", "yellow"],
    ["schwarz", "black"],
    ["weiß", "white"],
    ["grau", "grey"],
    ["braun", "brown"],
    ["bunt", "colourful"],
    ["die Größe", "size"],
    ["die Baumwolle", "cotton"],
    ["die Wolle", "wool"],
    ["anziehen", "to put on", "trennbar"],
    ["ausziehen", "to take off"],
    ["tragen", "to wear"],
    ["passen", "to fit", "Die Hose passt mir. (Dativ)"],
    ["stehen", "to suit", "Das Kleid steht dir gut."],
    ["eng / weit", "tight / loose"],
    ["kurz / lang", "short / long"],
    ["schick", "smart, stylish"],
    ["bequem", "comfortable"],
  ],
  phrases: [
    ["Ich suche eine warme Jacke.", "I'm looking for a warm jacket. — Adjektivendung nach eine: -e"],
    ["Welche Größe haben Sie?", "What size are you?"],
    ["Die Hose passt mir nicht, sie ist zu eng.", "The trousers don't fit me, they're too tight. — passen + Dativ"],
    ["Das Kleid steht dir wirklich gut.", "That dress really suits you."],
    ["Haben Sie das auch in Blau?", "Do you have that in blue too?"],
    ["Wo ist die Umkleidekabine?", "Where's the changing room?"],
    ["Im Winter trage ich immer einen Schal.", "In winter I always wear a scarf."],
    ["Das ist mir zu teuer — haben Sie etwas Günstigeres?", "That's too expensive for me — do you have anything cheaper?"],
  ],
};

const ARBEIT = {
  intro:
    "Beruf und Arbeitsplatz kommen in fast jeder Vorstellungsrunde vor und sind ein Standardthema im Schreiben (Entschuldigung an den Chef, Nachricht an eine Kollegin). Merke: nach „als“ steht der Beruf ohne Artikel.",
  phrasesTitle: "Redemittel — über die Arbeit sprechen",
  words: [
    ["der Beruf", "profession"],
    ["die Arbeit", "work"],
    ["der Arbeitsplatz", "workplace"],
    ["die Stelle / der Job", "position, job"],
    ["die Firma", "company"],
    ["das Büro", "office"],
    ["der Chef / die Chefin", "boss"],
    ["der Kollege / die Kollegin", "colleague"],
    ["der Mitarbeiter / die Mitarbeiterin", "employee"],
    ["der Lehrer / die Lehrerin", "teacher"],
    ["der Arzt / die Ärztin", "doctor"],
    ["der Verkäufer / die Verkäuferin", "sales assistant"],
    ["der Koch / die Köchin", "cook"],
    ["der Kellner / die Kellnerin", "waiter", "AT: der Ober"],
    ["der Fahrer / die Fahrerin", "driver"],
    ["der Handwerker", "tradesperson"],
    ["die Krankenschwester / der Krankenpfleger", "nurse"],
    ["der Ingenieur / die Ingenieurin", "engineer"],
    ["der Friseur / die Friseurin", "hairdresser"],
    ["die Hausfrau / der Hausmann", "homemaker"],
    ["arbeiten als", "to work as", "ohne Artikel: als Kellner"],
    ["arbeitslos", "unemployed"],
    ["die Arbeitszeit", "working hours"],
    ["die Schicht", "shift"],
    ["Vollzeit / Teilzeit", "full time / part time"],
    ["der Lohn / das Gehalt", "wage / salary"],
    ["verdienen", "to earn"],
    ["der Urlaub", "holiday, leave", "AT/DE: Urlaub, nicht „Ferien“ (Schule)"],
    ["der Feierabend", "end of the working day"],
    ["die Überstunde", "hour of overtime"],
    ["die Besprechung", "meeting"],
    ["die Bewerbung", "job application"],
    ["sich bewerben um", "to apply for"],
    ["der Lebenslauf", "CV"],
    ["das Vorstellungsgespräch", "job interview"],
    ["die Erfahrung", "experience"],
    ["die Ausbildung", "vocational training"],
    ["kündigen", "to quit, to give notice"],
    ["anstrengend", "exhausting"],
    ["stressig", "stressful"],
    ["selbstständig", "self-employed"],
  ],
  phrases: [
    ["Ich arbeite als Verkäuferin in einem Supermarkt.", "I work as a sales assistant in a supermarket. — als + Beruf, ohne Artikel"],
    ["Ich bin seit fünf Jahren bei der Firma.", "I've been with the company for five years."],
    ["Meine Arbeit macht mir Spaß.", "I enjoy my work. — Spaß machen + Dativ"],
    ["Ich arbeite Teilzeit, dreißig Stunden pro Woche.", "I work part time, thirty hours a week."],
    ["Können wir die Besprechung verschieben?", "Could we postpone the meeting?"],
    ["Ich bin heute krank und kann leider nicht kommen.", "I'm ill today and unfortunately can't come. — der Klassiker im Schreiben-Teil"],
    ["Ich möchte mich um die Stelle bewerben.", "I'd like to apply for the position. — sich bewerben um + Akkusativ"],
    ["Die Arbeit ist anstrengend, aber interessant.", "The work is exhausting but interesting."],
  ],
};

const AUSBILDUNG = {
  intro:
    "Warum lernst du Deutsch? Diese Frage kommt fast sicher. Hier sind die Wörter für Schule, Kurs, Niveau und Lernstrategien — und die Sätze, mit denen du deine eigene Sprachbiografie erzählst.",
  phrasesTitle: "Redemittel — über das Lernen sprechen",
  words: [
    ["die Schule", "school"],
    ["der Kindergarten", "kindergarten"],
    ["die Grundschule", "primary school", "AT: die Volksschule"],
    ["das Gymnasium", "grammar school"],
    ["die Universität", "university", "kurz: die Uni"],
    ["der Kurs", "course"],
    ["der Sprachkurs", "language course"],
    ["die Volkshochschule", "adult education centre", "Abk.: VHS"],
    ["der Unterricht", "lessons, class"],
    ["die Stunde", "lesson, hour"],
    ["das Fach, die Fächer", "subject(s)"],
    ["der Lehrer / die Lehrerin", "teacher"],
    ["der Schüler / die Schülerin", "pupil"],
    ["der Student / die Studentin", "university student"],
    ["der Teilnehmer / die Teilnehmerin", "course participant"],
    ["lernen", "to learn, to study (for school)"],
    ["studieren", "to study (at university)"],
    ["üben", "to practise"],
    ["wiederholen", "to revise, to repeat"],
    ["verstehen", "to understand"],
    ["erklären", "to explain"],
    ["die Hausaufgabe", "homework"],
    ["die Prüfung", "exam"],
    ["der Test", "test"],
    ["bestehen", "to pass"],
    ["durchfallen", "to fail"],
    ["die Note", "grade, mark"],
    ["das Zeugnis", "report, certificate"],
    ["das Zertifikat", "certificate"],
    ["das Niveau", "level", "A1, A2, B1 …"],
    ["die Sprache", "language"],
    ["die Muttersprache", "native language"],
    ["die Fremdsprache", "foreign language"],
    ["das Wort, die Wörter", "word(s)"],
    ["der Wortschatz", "vocabulary"],
    ["die Grammatik", "grammar"],
    ["die Aussprache", "pronunciation"],
    ["der Fehler", "mistake"],
    ["das Wörterbuch", "dictionary"],
    ["fließend", "fluent"],
    ["ein bisschen", "a little"],
    ["Fortschritte machen", "to make progress"],
  ],
  phrases: [
    ["Ich lerne seit zwei Jahren Deutsch.", "I've been learning German for two years. — seit + Dativ, Präsens!"],
    ["Ich besuche einen Deutschkurs an der Volkshochschule.", "I attend a German course at the adult education centre."],
    ["Ich lerne Deutsch, weil ich in Österreich arbeiten möchte.", "I'm learning German because I want to work in Austria. — weil → Verb ans Ende"],
    ["Die Grammatik finde ich schwer, aber das Sprechen macht Spaß.", "I find the grammar hard, but speaking is fun."],
    ["Können Sie das bitte langsamer sagen?", "Could you say that more slowly, please?"],
    ["Was bedeutet dieses Wort?", "What does this word mean?"],
    ["Ich möchte die Prüfung im Juni machen.", "I'd like to take the exam in June. — eine Prüfung machen"],
    ["Ich habe die Prüfung bestanden!", "I passed the exam!"],
  ],
};

const FREIZEIT = {
  intro:
    "Hobbys sind das dankbarste Sprechen-Thema: Du kannst dich vorbereiten und mit gern, lieber, am liebsten sofort punkten. Achte auf die Konstruktionen — Fußball spielen, Rad fahren, ins Kino gehen.",
  phrasesTitle: "Redemittel — über Hobbys sprechen",
  words: [
    ["die Freizeit", "free time"],
    ["das Hobby", "hobby"],
    ["der Sport", "sport"],
    ["Sport machen / treiben", "to do sport"],
    ["der Fußball", "football"],
    ["das Schwimmen", "swimming"],
    ["das Fahrrad", "bicycle", "Rad fahren, ich fahre Rad"],
    ["wandern", "to hike"],
    ["der Berg, die Berge", "mountain(s)"],
    ["Ski fahren", "to ski", "AT: sehr häufiges Thema"],
    ["der Verein", "club, association"],
    ["das Fitnessstudio", "gym"],
    ["die Musik", "music"],
    ["das Instrument", "instrument"],
    ["Klavier spielen", "to play the piano", "ohne Artikel"],
    ["die Gitarre", "guitar"],
    ["singen", "to sing"],
    ["tanzen", "to dance"],
    ["das Konzert", "concert"],
    ["das Kino", "cinema"],
    ["der Film", "film"],
    ["das Theater", "theatre"],
    ["das Museum", "museum"],
    ["die Ausstellung", "exhibition"],
    ["lesen", "to read"],
    ["das Buch", "book"],
    ["der Roman", "novel"],
    ["malen / zeichnen", "to paint / to draw"],
    ["fotografieren", "to take photos"],
    ["kochen / backen", "to cook / to bake"],
    ["der Garten", "garden"],
    ["das Spiel", "game"],
    ["Karten spielen", "to play cards"],
    ["sich treffen mit", "to meet up with"],
    ["ausgehen", "to go out"],
    ["sich entspannen", "to relax"],
    ["die Langeweile", "boredom"],
    ["langweilig / spannend", "boring / exciting"],
    ["gern / lieber / am liebsten", "gladly / rather / most of all"],
    ["Spaß machen", "to be fun", "Das macht mir Spaß."],
    ["sich interessieren für", "to be interested in"],
    ["die Lust", "desire", "Ich habe Lust auf …"],
  ],
  phrases: [
    ["In meiner Freizeit spiele ich gern Fußball.", "In my free time I like playing football. — gern + Verb"],
    ["Ich interessiere mich sehr für Musik.", "I'm very interested in music. — reflexiv + für + Akkusativ"],
    ["Am liebsten gehe ich mit Freunden ins Kino.", "Most of all I like going to the cinema with friends."],
    ["Am Wochenende wandere ich oft in den Bergen.", "At the weekend I often hike in the mountains."],
    ["Ich lese lieber, als fernzusehen.", "I'd rather read than watch TV."],
    ["Hast du Lust, am Samstag schwimmen zu gehen?", "Do you fancy going swimming on Saturday? — Lust haben zu + Infinitiv"],
    ["Das macht mir großen Spaß.", "I really enjoy that. — Spaß machen + Dativ"],
    ["Ich bin seit zehn Jahren in einem Sportverein.", "I've been in a sports club for ten years."],
  ],
};

export const THEMES3 = {
  "koerper-gesundheit": GESUNDHEIT,
  kleidung: KLEIDUNG,
  "arbeit-beruf": ARBEIT,
  "ausbildung-sprachen": AUSBILDUNG,
  "freizeit-hobbys": FREIZEIT,
};
