// Vocabulary Themen, part four: travel, the city, weather, media, time.

const REISEN = {
  intro:
    "Reisen und Verkehr sind der häufigste Hören-Kontext überhaupt: Durchsagen am Bahnhof, Verspätungen, Gleiswechsel. Lerne die Wörter, aber vor allem die Zahlen und die typischen Durchsagesätze.",
  phrasesTitle: "Redemittel — unterwegs",
  words: [
    ["die Reise", "journey, trip"],
    ["reisen", "to travel"],
    ["der Urlaub", "holiday"],
    ["der Bahnhof", "train station"],
    ["der Zug", "train"],
    ["die Bahn", "railway", "AT: ÖBB, DE: DB"],
    ["die S-Bahn / die U-Bahn", "suburban / underground train"],
    ["die Straßenbahn", "tram", "AT: die Bim (ugs.)"],
    ["der Bus", "bus"],
    ["die Haltestelle", "stop"],
    ["das Gleis", "platform, track"],
    ["der Bahnsteig", "platform"],
    ["die Fahrkarte / das Ticket", "ticket"],
    ["der Fahrplan", "timetable"],
    ["die Abfahrt / die Ankunft", "departure / arrival"],
    ["abfahren / ankommen", "to depart / to arrive"],
    ["umsteigen", "to change (trains)"],
    ["einsteigen / aussteigen", "to get on / to get off"],
    ["die Verspätung", "delay"],
    ["die Durchsage", "announcement"],
    ["einfach / hin und zurück", "one way / return"],
    ["erste / zweite Klasse", "first / second class"],
    ["der Sitzplatz", "seat"],
    ["reservieren", "to reserve"],
    ["das Flugzeug", "aeroplane"],
    ["der Flughafen", "airport"],
    ["der Flug", "flight"],
    ["fliegen", "to fly"],
    ["das Auto", "car"],
    ["fahren", "to drive, to go (by vehicle)"],
    ["der Führerschein", "driving licence"],
    ["die Tankstelle", "petrol station"],
    ["der Stau", "traffic jam"],
    ["das Gepäck", "luggage"],
    ["der Koffer", "suitcase"],
    ["der Rucksack", "rucksack"],
    ["das Hotel", "hotel"],
    ["die Jugendherberge", "youth hostel"],
    ["die Unterkunft", "accommodation"],
    ["buchen", "to book"],
    ["die Rezeption", "reception"],
    ["das Doppelzimmer / das Einzelzimmer", "double / single room"],
    ["die Übernachtung", "overnight stay"],
    ["die Grenze", "border"],
  ],
  phrases: [
    ["Einmal nach Salzburg, hin und zurück, bitte.", "One return to Salzburg, please. — the standard ticket request"],
    ["Wann fährt der nächste Zug nach Graz?", "When does the next train to Graz leave?"],
    ["Muss ich umsteigen?", "Do I have to change?"],
    ["Der Zug hat zehn Minuten Verspätung.", "The train is ten minutes late."],
    ["Der Zug fährt heute von Gleis 5 ab.", "The train departs from platform 5 today. — typische Durchsage"],
    ["Ich möchte ein Doppelzimmer für zwei Nächte reservieren.", "I'd like to reserve a double room for two nights."],
    ["Ist das Frühstück inklusive?", "Is breakfast included?"],
    ["Wir sind mit dem Auto gefahren.", "We went by car. — Perfekt mit sein"],
    ["Entschuldigung, ist dieser Platz noch frei?", "Excuse me, is this seat free?"],
  ],
};

const STADT = {
  intro:
    "„Wie komme ich zum Bahnhof?“ — Wegbeschreibungen sind eine feste Aufgabe im Hören und eine typische Rollensituation. Wichtig: die Richtungsangaben und die Präpositionen an, bei, gegenüber, um … herum.",
  phrasesTitle: "Redemittel — nach dem Weg fragen",
  words: [
    ["die Stadt", "city, town"],
    ["das Dorf", "village"],
    ["das Zentrum / die Innenstadt", "centre / city centre"],
    ["der Stadtteil", "district"],
    ["der Platz", "square"],
    ["die Straße", "street"],
    ["die Kreuzung", "crossroads"],
    ["die Ampel", "traffic light"],
    ["die Ecke", "corner"],
    ["die Brücke", "bridge"],
    ["der Park", "park"],
    ["das Rathaus", "town hall"],
    ["die Kirche", "church"],
    ["der Dom", "cathedral"],
    ["das Schloss", "palace, castle"],
    ["die Burg", "fortress"],
    ["das Museum", "museum"],
    ["die Post", "post office"],
    ["die Bank", "bank"],
    ["die Bibliothek", "library"],
    ["das Schwimmbad", "swimming pool"],
    ["die Sehenswürdigkeit", "sight, attraction"],
    ["die Touristeninformation", "tourist information"],
    ["der Stadtplan", "city map"],
    ["die Wegbeschreibung", "directions"],
    ["geradeaus", "straight ahead"],
    ["links / rechts", "left / right"],
    ["abbiegen", "to turn off"],
    ["nach links / rechts abbiegen", "to turn left / right"],
    ["die erste Straße links", "the first street on the left"],
    ["bis zur Ampel", "as far as the traffic light"],
    ["an … vorbei", "past …"],
    ["gegenüber von", "opposite"],
    ["neben", "next to"],
    ["zwischen", "between"],
    ["in der Nähe von", "near"],
    ["weit / nah", "far / near"],
    ["zu Fuß", "on foot"],
    ["die Richtung", "direction"],
    ["sich verlaufen", "to get lost (on foot)"],
    ["suchen / finden", "to look for / to find"],
    ["etwa / ungefähr", "roughly, about"],
  ],
  phrases: [
    ["Entschuldigung, wie komme ich zum Bahnhof?", "Excuse me, how do I get to the station? — zu + dem = zum"],
    ["Gehen Sie geradeaus bis zur Ampel.", "Go straight on as far as the traffic light."],
    ["Dann biegen Sie links ab.", "Then turn left. — biegen … ab, trennbar"],
    ["Das Museum ist gegenüber vom Rathaus.", "The museum is opposite the town hall."],
    ["Gibt es hier in der Nähe eine Apotheke?", "Is there a pharmacy near here?"],
    ["Wie weit ist es zu Fuß?", "How far is it on foot?"],
    ["Ungefähr zehn Minuten.", "About ten minutes."],
    ["Ich glaube, ich habe mich verlaufen.", "I think I've got lost."],
    ["Tut mir leid, ich bin auch fremd hier.", "Sorry, I'm not from around here either."],
  ],
};

const WETTER = {
  intro:
    "Wetter ist Smalltalk Nummer eins und ein sicheres Hören-Thema (die Vorhersage). Die Konstruktionen sind eigen: „es ist“, „es gibt“, „es regnet“ — alles mit dem unpersönlichen es.",
  phrasesTitle: "Redemittel — über das Wetter reden",
  words: [
    ["das Wetter", "weather"],
    ["die Wettervorhersage", "weather forecast"],
    ["die Sonne", "sun"],
    ["sonnig", "sunny"],
    ["die Wolke", "cloud"],
    ["bewölkt / wolkig", "cloudy"],
    ["der Regen", "rain"],
    ["regnen", "to rain", "Es regnet."],
    ["der Schnee", "snow"],
    ["schneien", "to snow"],
    ["der Wind", "wind"],
    ["windig", "windy"],
    ["das Gewitter", "thunderstorm"],
    ["der Nebel", "fog"],
    ["neblig", "foggy"],
    ["das Eis / glatt", "ice / slippery"],
    ["die Temperatur", "temperature"],
    ["der Grad", "degree", "15 Grad"],
    ["warm / heiß", "warm / hot"],
    ["kalt / kühl", "cold / cool"],
    ["mild", "mild"],
    ["trocken / nass", "dry / wet"],
    ["die Jahreszeit", "season"],
    ["der Frühling", "spring"],
    ["der Sommer", "summer"],
    ["der Herbst", "autumn"],
    ["der Winter", "winter"],
    ["der Monat", "month"],
    ["der Himmel", "sky"],
    ["die Luft", "air"],
    ["die Sonne scheint", "the sun is shining"],
    ["der Schirm / der Regenschirm", "umbrella"],
    ["die Sonnenbrille", "sunglasses"],
    ["frieren", "to freeze, to be cold"],
    ["schwitzen", "to sweat"],
    ["das Klima", "climate"],
    ["die Hitze / die Kälte", "heat / cold"],
    ["bei schönem Wetter", "in nice weather"],
    ["draußen / drinnen", "outside / inside"],
    ["der Grad unter null", "degrees below zero"],
  ],
  phrases: [
    ["Wie ist das Wetter heute?", "What's the weather like today?"],
    ["Es regnet seit heute Morgen.", "It's been raining since this morning."],
    ["Heute ist es sonnig und warm, etwa 25 Grad.", "Today it's sunny and warm, about 25 degrees."],
    ["Morgen soll es schneien.", "It's supposed to snow tomorrow. — sollen für Vorhersagen"],
    ["Im Winter ist es hier sehr kalt.", "In winter it's very cold here. — im + Jahreszeit"],
    ["Nimm einen Schirm mit, es gibt ein Gewitter.", "Take an umbrella, there'll be a thunderstorm."],
    ["Bei schönem Wetter gehen wir spazieren.", "In nice weather we go for a walk."],
    ["Mir ist kalt.", "I'm cold. — Dativ! nicht „ich bin kalt“"],
  ],
};

const TECHNIK = {
  intro:
    "Handy, E-Mail, Internet — dieser Wortschatz taucht im Schreiben-Teil auf (eine kurze Nachricht schreiben) und in Anzeigen im Lesen-Teil. Die meisten Wörter sind international, die Verben aber nicht.",
  phrasesTitle: "Redemittel — Nachrichten und Telefon",
  words: [
    ["das Handy", "mobile phone", "kein englisches Wort im DE/AT-Sinn!"],
    ["das Smartphone", "smartphone"],
    ["das Telefon", "telephone"],
    ["anrufen", "to call", "trennbar: ich rufe … an"],
    ["der Anruf", "phone call"],
    ["die Nummer wählen", "to dial the number"],
    ["klingeln", "to ring"],
    ["zurückrufen", "to call back"],
    ["die Nachricht", "message"],
    ["die SMS", "text message"],
    ["schreiben", "to write"],
    ["die E-Mail", "email"],
    ["die Mailbox", "voicemail"],
    ["der Computer", "computer"],
    ["der Laptop", "laptop"],
    ["der Drucker", "printer"],
    ["die Tastatur", "keyboard"],
    ["der Bildschirm", "screen"],
    ["das Internet", "internet"],
    ["die Webseite", "website"],
    ["online / offline", "online / offline"],
    ["das WLAN", "Wi-Fi", "gesprochen: „we-lan“"],
    ["das Passwort", "password"],
    ["herunterladen", "to download"],
    ["speichern", "to save"],
    ["löschen", "to delete"],
    ["die Datei", "file"],
    ["der Anhang", "attachment"],
    ["die App", "app"],
    ["das soziale Netzwerk", "social network"],
    ["das Fernsehen", "television"],
    ["der Fernseher", "TV set"],
    ["das Radio", "radio"],
    ["die Zeitung", "newspaper"],
    ["die Zeitschrift", "magazine"],
    ["die Nachrichten (Pl.)", "the news"],
    ["die Werbung", "advertising"],
    ["kaputt", "broken"],
    ["funktionieren", "to work, to function"],
    ["reparieren", "to repair"],
    ["ausschalten / einschalten", "to switch off / on"],
  ],
  phrases: [
    ["Kannst du mich später zurückrufen?", "Can you call me back later?"],
    ["Ich schreibe dir eine Nachricht.", "I'll send you a message."],
    ["Mein Handy ist kaputt.", "My phone is broken."],
    ["Wie ist das WLAN-Passwort?", "What's the Wi-Fi password?"],
    ["Ich habe deine E-Mail leider nicht bekommen.", "Unfortunately I didn't get your email."],
    ["Die Datei ist im Anhang.", "The file is attached."],
    ["Ich rufe dich morgen an.", "I'll call you tomorrow. — rufe … an"],
    ["Entschuldigung, ich habe mich verwählt.", "Sorry, I dialled the wrong number."],
    ["Im Internet habe ich eine gute Wohnung gefunden.", "I found a good flat on the internet."],
  ],
};

const TERMINE = {
  intro:
    "Uhrzeit und Termine sind der Kern der Hören-Aufgaben: kurze Ansagen mit einer Zahl, die du richtig verstehen musst. Die Falle ist die offizielle Uhrzeit (14:30) gegen die umgangssprachliche (halb drei) — und „halb drei“ heißt 2:30, nicht 3:30!",
  phrasesTitle: "Redemittel — Termine ausmachen",
  words: [
    ["die Zeit", "time"],
    ["die Uhr", "clock, watch"],
    ["die Uhrzeit", "time of day"],
    ["die Stunde", "hour"],
    ["die Minute", "minute"],
    ["die Sekunde", "second"],
    ["die Viertelstunde", "quarter of an hour"],
    ["halb", "half", "halb drei = 2:30!"],
    ["Viertel nach / Viertel vor", "quarter past / quarter to"],
    ["der Termin", "appointment"],
    ["die Verabredung", "date, arrangement"],
    ["der Kalender", "calendar"],
    ["der Tag", "day"],
    ["die Woche", "week"],
    ["der Monat", "month"],
    ["das Jahr", "year"],
    ["Montag, Dienstag, Mittwoch", "Monday, Tuesday, Wednesday"],
    ["Donnerstag, Freitag, Samstag", "Thursday, Friday, Saturday", "AT auch: der Samstag/Sonnabend"],
    ["Sonntag", "Sunday"],
    ["das Wochenende", "weekend"],
    ["der Werktag", "working day"],
    ["der Morgen / der Vormittag", "morning / late morning"],
    ["der Mittag / der Nachmittag", "midday / afternoon"],
    ["der Abend / die Nacht", "evening / night"],
    ["heute / morgen / gestern", "today / tomorrow / yesterday"],
    ["übermorgen / vorgestern", "day after tomorrow / day before yesterday"],
    ["vorher / nachher", "before / afterwards"],
    ["pünktlich", "punctual, on time"],
    ["die Verspätung", "delay"],
    ["sich verspäten", "to be late"],
    ["warten auf", "to wait for", "+ Akkusativ"],
    ["dauern", "to last, to take (time)"],
    ["ausmachen", "to arrange"],
    ["absagen", "to cancel"],
    ["verschieben", "to postpone"],
    ["passen", "to suit", "Passt dir Montag?"],
    ["frei haben", "to be off work"],
    ["Zeit haben", "to have time"],
    ["bis", "until"],
    ["ab", "from (a time on)"],
    ["gegen", "around (a time)"],
    ["um … Uhr", "at … o'clock"],
  ],
  phrases: [
    ["Wie spät ist es? — Es ist Viertel nach drei.", "What time is it? — It's a quarter past three."],
    ["Der Kurs beginnt um halb neun.", "The course starts at half past eight. — halb neun = 8:30"],
    ["Der Zug fährt um vierzehn Uhr dreißig.", "The train leaves at 14:30. — offizielle Uhrzeit"],
    ["Wann hast du Zeit?", "When are you free?"],
    ["Passt dir Dienstag um sechs?", "Does Tuesday at six suit you? — passen + Dativ"],
    ["Können wir den Termin verschieben?", "Could we postpone the appointment?"],
    ["Ich muss den Termin leider absagen.", "Unfortunately I have to cancel the appointment."],
    ["Ich komme etwas später, tut mir leid.", "I'll be a bit late, sorry."],
    ["Wie lange dauert der Film?", "How long does the film last?"],
  ],
};

export const THEMES4 = {
  "reisen-verkehr": REISEN,
  "orientierung-stadt": STADT,
  "wetter-klima": WETTER,
  "technik-medien": TECHNIK,
  "termine-uhrzeit": TERMINE,
};
