// Vocabulary Themen, part two: the personal-life cluster.
// note (third entry) = Austrian variant or usage hint, relevant for the ÖSD.

const PERSON = {
  intro:
    "Der allererste Prüfungsmoment: Sie stellen sich vor. In Sprechen Teil 1 fragt die Prüferin genau nach diesen Angaben, und im Schreiben-Teil füllst du oft ein Formular mit ihnen aus. Diese Wörter musst du ohne Nachdenken können.",
  phrasesTitle: "Redemittel — sich vorstellen",
  words: [
    ["der Name", "name"],
    ["der Vorname", "first name"],
    ["der Familienname", "surname", "auch: der Nachname"],
    ["heißen", "to be called"],
    ["das Alter", "age"],
    ["das Geburtsdatum", "date of birth"],
    ["der Geburtsort", "place of birth"],
    ["geboren sein", "to be born"],
    ["die Staatsangehörigkeit", "nationality"],
    ["das Heimatland", "home country"],
    ["die Adresse", "address"],
    ["die Straße", "street", "Abk.: Str."],
    ["die Hausnummer", "house number"],
    ["die Postleitzahl", "postcode", "Abk.: PLZ"],
    ["der Wohnort", "place of residence"],
    ["die Telefonnummer", "phone number"],
    ["die Handynummer", "mobile number", "AT/DE: Handy, nicht „Mobile“"],
    ["die E-Mail-Adresse", "email address"],
    ["der Familienstand", "marital status"],
    ["ledig", "single"],
    ["verheiratet", "married"],
    ["geschieden", "divorced"],
    ["der Beruf", "profession"],
    ["berufstätig", "employed, working"],
    ["die Muttersprache", "native language"],
    ["die Unterschrift", "signature"],
    ["das Formular", "form"],
    ["ausfüllen", "to fill in"],
    ["der Ausweis", "ID card"],
    ["der Reisepass", "passport"],
    ["buchstabieren", "to spell"],
    ["wiederholen", "to repeat"],
    ["sich vorstellen", "to introduce oneself"],
    ["angeben", "to state, to give (details)"],
    ["seit", "since, for (duration)"],
    ["die Anmeldung", "registration"],
  ],
  phrases: [
    ["Ich heiße Maria Bauer.", "My name is Maria Bauer. — heißen, not „mein Name ist“ in speech"],
    ["Darf ich mich vorstellen?", "May I introduce myself? — the polite opener"],
    ["Ich komme aus der Türkei und wohne seit drei Jahren in Wien.", "I'm from Turkey and have lived in Vienna for three years. — seit + Dativ, Präsens!"],
    ["Ich bin 34 Jahre alt.", "I'm 34 years old."],
    ["Ich bin verheiratet und habe zwei Kinder.", "I'm married and have two children."],
    ["Meine Muttersprache ist Arabisch, aber ich spreche auch Englisch.", "My native language is Arabic, but I also speak English."],
    ["Wie schreibt man das?", "How do you spell that?"],
    ["Können Sie das bitte buchstabieren?", "Could you spell that, please?"],
    ["Entschuldigung, können Sie das bitte wiederholen?", "Sorry, could you repeat that? — safest sentence in the whole exam"],
  ],
};

const FAMILIE = {
  intro:
    "Über die Familie zu sprechen ist ein Standardthema in Sprechen Teil 1 und ein häufiges Schreiben-Thema (Einladung, Bericht an eine Freundin). Achte auf die Possessivartikel — mein Bruder, meine Schwester, meine Eltern.",
  phrasesTitle: "Redemittel — über die Familie sprechen",
  words: [
    ["die Familie", "family"],
    ["die Eltern (Pl.)", "parents"],
    ["die Mutter", "mother"],
    ["der Vater", "father"],
    ["das Kind, die Kinder", "child, children"],
    ["die Tochter", "daughter"],
    ["der Sohn", "son"],
    ["die Geschwister (Pl.)", "siblings"],
    ["die Schwester", "sister"],
    ["der Bruder", "brother"],
    ["die Großeltern (Pl.)", "grandparents"],
    ["die Oma / die Großmutter", "grandma / grandmother"],
    ["der Opa / der Großvater", "grandpa / grandfather"],
    ["der Enkel / die Enkelin", "grandson / granddaughter"],
    ["die Tante", "aunt"],
    ["der Onkel", "uncle"],
    ["der Cousin / die Cousine", "cousin (m/f)"],
    ["die Verwandten (Pl.)", "relatives"],
    ["der Ehemann / die Ehefrau", "husband / wife"],
    ["der Partner / die Partnerin", "partner"],
    ["der Freund / die Freundin", "friend; boyfriend/girlfriend", "Kontext entscheidet!"],
    ["der Nachbar / die Nachbarin", "neighbour"],
    ["der Kollege / die Kollegin", "colleague"],
    ["heiraten", "to marry"],
    ["die Hochzeit", "wedding"],
    ["sich trennen", "to separate"],
    ["zusammen wohnen", "to live together"],
    ["sich kümmern um", "to look after"],
    ["sich verstehen mit", "to get on with"],
    ["sich streiten", "to argue"],
    ["besuchen", "to visit"],
    ["älter / jünger als", "older / younger than"],
    ["das Einzelkind", "only child"],
    ["allein erziehend", "single-parent"],
    ["die Verwandtschaft", "the extended family"],
    ["das Familienfoto", "family photo"],
  ],
  phrases: [
    ["Ich habe einen Bruder und zwei Schwestern.", "I have one brother and two sisters."],
    ["Mein Bruder ist zwei Jahre älter als ich.", "My brother is two years older than me. — Komparativ + als"],
    ["Meine Eltern wohnen noch in der Türkei.", "My parents still live in Turkey."],
    ["Ich verstehe mich gut mit meiner Schwester.", "I get on well with my sister. — reflexiv + mit + Dativ"],
    ["Wir besuchen meine Großeltern jeden Sonntag.", "We visit my grandparents every Sunday."],
    ["Ich bin ein Einzelkind.", "I'm an only child."],
    ["Meine Frau arbeitet als Krankenschwester.", "My wife works as a nurse. — als + Beruf, ohne Artikel"],
    ["Wir haben letztes Jahr geheiratet.", "We got married last year. — Perfekt: haben geheiratet"],
  ],
};

const WOHNEN = {
  intro:
    "Wohnen ist eines der drei häufigsten Sprechen-Themen und taucht im Lesen-Teil als Wohnungsanzeige auf. Lerne die Zimmer, die Möbel und die Sätze, mit denen man eine Wohnung beschreibt und bewertet.",
  phrasesTitle: "Redemittel — die eigene Wohnung beschreiben",
  words: [
    ["die Wohnung", "flat, apartment"],
    ["das Haus", "house"],
    ["das Zimmer", "room"],
    ["das Wohnzimmer", "living room"],
    ["das Schlafzimmer", "bedroom"],
    ["die Küche", "kitchen"],
    ["das Bad / das Badezimmer", "bathroom"],
    ["die Toilette", "toilet", "AT/CH oft: das WC"],
    ["der Flur", "hallway", "AT: das Vorzimmer"],
    ["der Balkon", "balcony"],
    ["der Garten", "garden"],
    ["der Keller", "cellar, basement"],
    ["der Stock / die Etage", "floor, storey"],
    ["der Aufzug", "lift", "AT: der Lift"],
    ["die Miete", "rent"],
    ["die Nebenkosten (Pl.)", "utilities, service charges"],
    ["der Vermieter / die Vermieterin", "landlord / landlady"],
    ["der Mieter / die Mieterin", "tenant"],
    ["mieten", "to rent (as tenant)"],
    ["vermieten", "to rent out"],
    ["umziehen", "to move house"],
    ["der Umzug", "the move"],
    ["die Möbel (Pl.)", "furniture"],
    ["der Tisch", "table"],
    ["der Stuhl", "chair"],
    ["das Sofa", "sofa"],
    ["der Sessel", "armchair", "AT: der Sessel = Stuhl!"],
    ["das Bett", "bed"],
    ["der Schrank", "wardrobe, cupboard"],
    ["das Regal", "shelf"],
    ["die Lampe", "lamp"],
    ["der Teppich", "carpet, rug"],
    ["der Herd", "cooker, stove"],
    ["der Kühlschrank", "fridge"],
    ["die Waschmaschine", "washing machine"],
    ["hell / dunkel", "bright / dark"],
    ["gemütlich", "cosy"],
    ["günstig / teuer", "cheap / expensive"],
    ["möbliert", "furnished"],
    ["der Quadratmeter", "square metre", "Abk.: m²"],
  ],
  phrases: [
    ["Ich wohne in einer Zweizimmerwohnung im dritten Stock.", "I live in a two-room flat on the third floor."],
    ["Die Wohnung hat 55 Quadratmeter.", "The flat is 55 square metres."],
    ["Die Miete beträgt 650 Euro plus Nebenkosten.", "The rent is €650 plus utilities."],
    ["Mein Zimmer ist klein, aber sehr gemütlich.", "My room is small but very cosy. — aber verbindet zwei Hauptsätze"],
    ["Wir suchen eine größere Wohnung.", "We're looking for a bigger flat."],
    ["Am liebsten sitze ich auf dem Balkon.", "I like sitting on the balcony best. — Wechselpräposition, wo? → Dativ"],
    ["Nächsten Monat ziehe ich um.", "I'm moving next month. — trennbares Verb: ziehe … um"],
    ["Gibt es einen Aufzug im Haus?", "Is there a lift in the building?"],
  ],
};

const ALLTAG = {
  intro:
    "Der Tagesablauf ist die Standardaufgabe für trennbare Verben und Reflexivverben — aufstehen, sich anziehen, wegfahren. In Sprechen Teil 1 wirst du fast sicher gefragt: Wie sieht ein normaler Tag bei Ihnen aus?",
  phrasesTitle: "Redemittel — den Tag beschreiben",
  words: [
    ["der Alltag", "everyday life"],
    ["der Tagesablauf", "daily routine"],
    ["aufstehen", "to get up", "trennbar: ich stehe auf"],
    ["aufwachen", "to wake up"],
    ["der Wecker", "alarm clock"],
    ["klingeln", "to ring"],
    ["sich duschen", "to shower"],
    ["sich waschen", "to wash"],
    ["sich die Zähne putzen", "to brush one's teeth", "Dativ: ich putze mir …"],
    ["sich anziehen", "to get dressed"],
    ["frühstücken", "to have breakfast"],
    ["zur Arbeit fahren", "to travel to work"],
    ["anfangen / beginnen", "to start"],
    ["die Pause", "break"],
    ["die Mittagspause", "lunch break"],
    ["aufhören", "to stop, to finish"],
    ["der Feierabend", "end of the working day"],
    ["einkaufen", "to shop"],
    ["kochen", "to cook"],
    ["putzen", "to clean"],
    ["aufräumen", "to tidy up"],
    ["waschen", "to wash (clothes)"],
    ["spazieren gehen", "to go for a walk"],
    ["fernsehen", "to watch TV", "trennbar: ich sehe fern"],
    ["sich ausruhen", "to rest"],
    ["ins Bett gehen", "to go to bed"],
    ["einschlafen", "to fall asleep"],
    ["müde", "tired"],
    ["früh / spät", "early / late"],
    ["immer", "always"],
    ["meistens", "mostly, usually"],
    ["oft", "often"],
    ["manchmal", "sometimes"],
    ["selten", "rarely"],
    ["nie", "never"],
    ["jeden Tag", "every day", "Akkusativ ohne Präposition"],
    ["zuerst / dann / danach", "first / then / afterwards"],
    ["zum Schluss", "finally, at the end"],
  ],
  phrases: [
    ["Ich stehe jeden Tag um halb sieben auf.", "I get up at half past six every day. — halb sieben = 6:30!"],
    ["Zuerst dusche ich, dann frühstücke ich.", "First I shower, then I have breakfast."],
    ["Um acht fahre ich mit der U-Bahn zur Arbeit.", "At eight I take the underground to work."],
    ["Meine Arbeit fängt um neun an.", "My work starts at nine. — fängt … an"],
    ["Am Nachmittag hole ich die Kinder vom Kindergarten ab.", "In the afternoon I pick the kids up from kindergarten."],
    ["Abends koche ich und sehe ein bisschen fern.", "In the evenings I cook and watch a bit of TV."],
    ["Normalerweise gehe ich gegen elf ins Bett.", "I usually go to bed around eleven."],
    ["Am Wochenende schlafe ich länger.", "At the weekend I sleep in. — am + Tag/Wochenende"],
  ],
};

const EINKAUFEN = {
  intro:
    "Einkaufen verbindet Wortschatz, Zahlen und Höflichkeit — und ist eine typische Rollensituation im Sprechen-Teil. Wichtig sind die Mengenangaben (ein Kilo, eine Packung) und die Sätze für Reklamation und Umtausch.",
  phrasesTitle: "Redemittel — im Geschäft",
  words: [
    ["das Geschäft / der Laden", "shop"],
    ["der Supermarkt", "supermarket"],
    ["die Bäckerei", "bakery"],
    ["die Metzgerei", "butcher's", "AT: die Fleischhauerei"],
    ["die Apotheke", "pharmacy"],
    ["das Kaufhaus", "department store"],
    ["der Markt", "market"],
    ["die Kasse", "checkout, till"],
    ["der Verkäufer / die Verkäuferin", "shop assistant"],
    ["der Kunde / die Kundin", "customer"],
    ["der Einkaufswagen", "shopping trolley"],
    ["die Tüte", "bag", "AT: das Sackerl"],
    ["der Preis", "price"],
    ["kosten", "to cost"],
    ["billig / günstig", "cheap / good value"],
    ["teuer", "expensive"],
    ["das Angebot", "special offer"],
    ["der Rabatt", "discount"],
    ["im Sonderangebot", "on special offer"],
    ["das Kilo / das Gramm", "kilo / gram"],
    ["der Liter", "litre"],
    ["die Packung", "packet"],
    ["die Flasche", "bottle"],
    ["die Dose", "tin, can"],
    ["das Stück", "piece, item"],
    ["ein bisschen / etwas", "a little"],
    ["viel / wenig", "much / little"],
    ["die Größe", "size"],
    ["anprobieren", "to try on"],
    ["umtauschen", "to exchange"],
    ["zurückgeben", "to return"],
    ["der Kassenbon / die Quittung", "receipt"],
    ["bar bezahlen", "to pay cash"],
    ["mit Karte bezahlen", "to pay by card"],
    ["das Kleingeld", "change (coins)"],
    ["die Öffnungszeiten (Pl.)", "opening hours"],
    ["geöffnet / geschlossen", "open / closed"],
    ["ausverkauft", "sold out"],
  ],
  phrases: [
    ["Ich hätte gern ein Kilo Tomaten.", "I'd like a kilo of tomatoes. — Konjunktiv II, höflich"],
    ["Was kostet das?", "How much is that?"],
    ["Haben Sie das auch in Größe 40?", "Do you have that in size 40 too?"],
    ["Kann ich das anprobieren?", "Can I try this on?"],
    ["Das ist mir zu teuer.", "That's too expensive for me. — zu + Adjektiv = too …"],
    ["Zahlen Sie bar oder mit Karte?", "Are you paying cash or by card? — what the cashier asks"],
    ["Ich möchte das umtauschen. Hier ist die Quittung.", "I'd like to exchange this. Here's the receipt."],
    ["Wann haben Sie geöffnet?", "When are you open?"],
    ["Sonst noch etwas?", "Anything else? — the classic shop question"],
  ],
};

export const THEMES2 = {
  "persoenliche-informationen": PERSON,
  familie: FAMILIE,
  wohnen: WOHNEN,
  "alltag-tagesablauf": ALLTAG,
  einkaufen: EINKAUFEN,
};
