// Vocabulary Themen, part five: festivals, environment, money, origins.

const FESTE = {
  intro:
    "Einladungen schreiben, zusagen, absagen — das ist eine der wahrscheinlichsten Schreiben-Aufgaben überhaupt. Dazu die Feste im deutschsprachigen Raum, die in Lesetexten als bekannt vorausgesetzt werden.",
  phrasesTitle: "Redemittel — einladen, zu- und absagen",
  words: [
    ["das Fest", "celebration, festival"],
    ["die Feier", "party, celebration"],
    ["feiern", "to celebrate"],
    ["der Feiertag", "public holiday"],
    ["der Geburtstag", "birthday"],
    ["die Party", "party"],
    ["die Einladung", "invitation"],
    ["einladen", "to invite", "trennbar: ich lade … ein"],
    ["der Gast, die Gäste", "guest(s)"],
    ["das Geschenk", "present"],
    ["schenken", "to give (as a gift)"],
    ["gratulieren", "to congratulate", "+ Dativ"],
    ["Weihnachten", "Christmas"],
    ["der Heilige Abend", "Christmas Eve", "24.12., der Hauptabend"],
    ["der Weihnachtsmarkt", "Christmas market", "AT: der Christkindlmarkt"],
    ["Silvester", "New Year's Eve"],
    ["Neujahr", "New Year's Day"],
    ["Ostern", "Easter"],
    ["Pfingsten", "Whitsun"],
    ["der Fasching / der Karneval", "carnival", "AT/Bayern: Fasching"],
    ["das Oktoberfest", "Oktoberfest"],
    ["der Nationalfeiertag", "national holiday", "AT: 26. Oktober"],
    ["die Hochzeit", "wedding"],
    ["die Taufe", "christening"],
    ["das Jubiläum", "anniversary"],
    ["die Tradition", "tradition"],
    ["der Brauch", "custom"],
    ["die Kerze", "candle"],
    ["der Weihnachtsbaum", "Christmas tree", "AT: der Christbaum"],
    ["das Feuerwerk", "fireworks"],
    ["der Kuchen / die Torte", "cake / gateau"],
    ["anstoßen", "to clink glasses, to toast"],
    ["die Rede", "speech"],
    ["die Karte", "card"],
    ["die Blumen (Pl.)", "flowers"],
    ["zusagen / absagen", "to accept / to decline"],
    ["sich freuen auf", "to look forward to"],
    ["mitbringen", "to bring along"],
    ["stattfinden", "to take place"],
    ["Herzlichen Glückwunsch!", "Congratulations!"],
    ["Alles Gute!", "All the best!"],
    ["Prost!", "Cheers!"],
  ],
  phrases: [
    ["Ich möchte dich zu meinem Geburtstag einladen.", "I'd like to invite you to my birthday. — zu + Dativ"],
    ["Die Party findet am Samstag um acht bei mir statt.", "The party takes place on Saturday at eight at my place. — findet … statt"],
    ["Vielen Dank für die Einladung, ich komme gern!", "Thanks a lot for the invitation, I'd love to come!"],
    ["Leider kann ich nicht kommen, weil ich arbeiten muss.", "Unfortunately I can't come because I have to work. — weil → Verb ans Ende"],
    ["Soll ich etwas mitbringen?", "Should I bring something?"],
    ["Herzlichen Glückwunsch zum Geburtstag!", "Happy birthday!"],
    ["Ich freue mich schon sehr auf das Fest.", "I'm really looking forward to the party. — sich freuen auf + Akkusativ"],
    ["Frohe Weihnachten und einen guten Rutsch!", "Merry Christmas and a good start to the new year!"],
  ],
};

const UMWELT = {
  intro:
    "Umwelt ist auf A2 ein einfaches Alltagsthema: Müll trennen, Strom sparen, mit dem Rad fahren. Es taucht als Lesetext (Aushang im Haus) und als Meinungsfrage im Sprechen auf — dort brauchst du vor allem „ich finde … weil“.",
  phrasesTitle: "Redemittel — Meinung zur Umwelt",
  words: [
    ["die Umwelt", "environment"],
    ["die Natur", "nature"],
    ["der Umweltschutz", "environmental protection"],
    ["schützen", "to protect"],
    ["der Müll", "rubbish, waste", "AT auch: der Mist"],
    ["die Mülltonne", "bin"],
    ["den Müll trennen", "to separate waste"],
    ["das Altpapier", "waste paper"],
    ["das Glas", "glass"],
    ["der Kunststoff / das Plastik", "plastic"],
    ["der Biomüll", "organic waste"],
    ["recyceln", "to recycle"],
    ["das Pfand", "deposit (on bottles)"],
    ["die Mehrwegflasche", "reusable bottle"],
    ["wegwerfen", "to throw away"],
    ["sparen", "to save"],
    ["der Strom", "electricity"],
    ["die Energie", "energy"],
    ["das Wasser", "water"],
    ["das Licht ausmachen", "to turn off the light"],
    ["heizen", "to heat"],
    ["die Sonnenenergie", "solar energy"],
    ["die Luft", "air"],
    ["die Luftverschmutzung", "air pollution"],
    ["der Lärm", "noise"],
    ["das Klima", "climate"],
    ["der Klimawandel", "climate change"],
    ["das Auto stehen lassen", "to leave the car at home"],
    ["öffentliche Verkehrsmittel", "public transport"],
    ["das Fahrrad", "bicycle"],
    ["zu Fuß gehen", "to walk"],
    ["die Tüte", "plastic bag", "AT: das Sackerl"],
    ["die Stofftasche", "cloth bag"],
    ["regional / saisonal", "regional / seasonal"],
    ["der Bauernhof", "farm"],
    ["das Bio-Produkt", "organic product"],
    ["der Wald", "forest"],
    ["der See / der Fluss", "lake / river"],
    ["das Tier", "animal"],
    ["die Pflanze", "plant"],
    ["sauber / schmutzig", "clean / dirty"],
    ["umweltfreundlich", "environmentally friendly"],
  ],
  phrases: [
    ["Bei uns muss man den Müll trennen.", "Where I live you have to separate the waste. — man = one/you generally"],
    ["Papier kommt in die blaue Tonne.", "Paper goes in the blue bin."],
    ["Ich fahre meistens mit dem Rad zur Arbeit.", "I mostly cycle to work."],
    ["Man sollte weniger Plastik benutzen.", "One should use less plastic. — sollte, höflicher Rat"],
    ["Ich finde Umweltschutz sehr wichtig, weil wir nur eine Erde haben.", "I think environmental protection is very important because we only have one Earth."],
    ["Wir kaufen Obst und Gemüse auf dem Markt.", "We buy fruit and vegetables at the market."],
    ["Bitte machen Sie das Licht aus!", "Please turn off the light!"],
    ["Mit dem Zug ist man umweltfreundlicher unterwegs.", "You travel in a more environmentally friendly way by train."],
  ],
};

const GELD = {
  intro:
    "Zahlen verstehen ist die halbe Hören-Prüfung, und Geld ist der häufigste Kontext dafür. Dazu die Bank-Situation, die im Rollenspiel vorkommen kann, und die Formulierungen für teuer und billig.",
  phrasesTitle: "Redemittel — bezahlen und Preise",
  words: [
    ["das Geld", "money"],
    ["der Euro", "euro"],
    ["der Cent", "cent"],
    ["der Franken", "Swiss franc", "CH"],
    ["die Münze", "coin"],
    ["der Schein", "banknote"],
    ["das Kleingeld", "small change"],
    ["das Bargeld", "cash"],
    ["die Karte", "card"],
    ["die Kreditkarte", "credit card"],
    ["die Bank", "bank"],
    ["das Konto", "account"],
    ["die Kontonummer / die IBAN", "account number / IBAN"],
    ["der Geldautomat", "cash machine"],
    ["Geld abheben", "to withdraw money"],
    ["Geld überweisen", "to transfer money"],
    ["die Überweisung", "bank transfer"],
    ["einzahlen", "to pay in"],
    ["der Preis", "price"],
    ["kosten", "to cost"],
    ["bezahlen", "to pay"],
    ["die Rechnung", "bill, invoice"],
    ["die Quittung", "receipt"],
    ["das Trinkgeld", "tip", "in AT/DE üblich: aufrunden"],
    ["die Miete", "rent"],
    ["die Steuer", "tax"],
    ["die Versicherung", "insurance"],
    ["das Gehalt / der Lohn", "salary / wage"],
    ["verdienen", "to earn"],
    ["ausgeben", "to spend"],
    ["sparen", "to save"],
    ["das Sparkonto", "savings account"],
    ["leihen", "to lend, to borrow"],
    ["schulden", "to owe"],
    ["teuer / billig", "expensive / cheap"],
    ["günstig", "good value"],
    ["kostenlos / gratis", "free of charge"],
    ["die Gebühr", "fee"],
    ["das Sonderangebot", "special offer"],
    ["der Rabatt", "discount"],
    ["reich / arm", "rich / poor"],
    ["sich etwas leisten können", "to be able to afford something"],
  ],
  phrases: [
    ["Was kostet das zusammen?", "How much is that altogether?"],
    ["Das macht 12 Euro 50.", "That comes to €12.50. — wie es an der Kasse gesagt wird"],
    ["Kann ich mit Karte zahlen?", "Can I pay by card?"],
    ["Stimmt so.", "Keep the change. — beim Trinkgeld"],
    ["Ich möchte 200 Euro abheben.", "I'd like to withdraw €200."],
    ["Ich möchte ein Konto eröffnen.", "I'd like to open an account."],
    ["Das kann ich mir leider nicht leisten.", "I'm afraid I can't afford that."],
    ["Ich spare für ein neues Fahrrad.", "I'm saving for a new bike. — sparen für + Akkusativ"],
    ["Können Sie mir eine Quittung geben?", "Could you give me a receipt?"],
  ],
};

const HEIMAT = {
  intro:
    "„Erzählen Sie etwas über Ihr Heimatland“ — eine sichere Frage im Sprechen-Teil und ein häufiges Schreiben-Thema. Hier sind die Länder, die Nationalitäten und die Sätze über Umzug, Sprache und Kultur.",
  phrasesTitle: "Redemittel — über die Herkunft sprechen",
  words: [
    ["die Heimat", "home, homeland"],
    ["das Heimatland", "home country"],
    ["die Herkunft", "origin"],
    ["kommen aus", "to come from", "+ Dativ"],
    ["das Land, die Länder", "country, countries"],
    ["Österreich / österreichisch", "Austria / Austrian"],
    ["Deutschland / deutsch", "Germany / German"],
    ["die Schweiz", "Switzerland", "immer mit Artikel: in der Schweiz"],
    ["die Türkei / türkisch", "Turkey / Turkish"],
    ["Polen / polnisch", "Poland / Polish"],
    ["Italien / italienisch", "Italy / Italian"],
    ["Syrien / syrisch", "Syria / Syrian"],
    ["die Nationalität", "nationality"],
    ["der Ausländer / die Ausländerin", "foreigner"],
    ["der Einwanderer / die Einwanderin", "immigrant"],
    ["auswandern / einwandern", "to emigrate / to immigrate"],
    ["umziehen", "to move"],
    ["die Hauptstadt", "capital city"],
    ["die Region", "region"],
    ["das Meer", "sea"],
    ["die Berge (Pl.)", "mountains"],
    ["die Landschaft", "landscape"],
    ["die Kultur", "culture"],
    ["die Sitte / der Brauch", "custom"],
    ["die Religion", "religion"],
    ["die Küche", "cuisine"],
    ["die Spezialität", "speciality"],
    ["die Sprache", "language"],
    ["der Dialekt", "dialect", "in AT sehr verbreitet"],
    ["die Muttersprache", "native language"],
    ["die Aufenthaltserlaubnis", "residence permit"],
    ["die Behörde / das Amt", "authority / public office"],
    ["die Anmeldung", "registration"],
    ["die Integration", "integration"],
    ["sich wohlfühlen", "to feel at home, comfortable"],
    ["vermissen", "to miss"],
    ["das Heimweh", "homesickness"],
    ["fremd", "foreign, unfamiliar"],
    ["der Unterschied", "difference"],
    ["ähnlich", "similar"],
    ["typisch", "typical"],
    ["die Erfahrung", "experience"],
  ],
  phrases: [
    ["Ich komme aus Syrien und lebe seit vier Jahren in Wien.", "I'm from Syria and have lived in Vienna for four years."],
    ["Meine Heimatstadt liegt im Süden des Landes.", "My home town is in the south of the country."],
    ["In meinem Land isst man viel Reis.", "In my country people eat a lot of rice. — man + Verb"],
    ["Das Wetter ist bei uns viel wärmer als hier.", "The weather at home is much warmer than here. — Komparativ + als"],
    ["Ich vermisse meine Familie sehr.", "I miss my family very much."],
    ["Hier gefällt es mir gut, die Leute sind freundlich.", "I like it here, the people are friendly. — gefallen + Dativ"],
    ["Der größte Unterschied ist das Essen.", "The biggest difference is the food."],
    ["In Österreich spricht man viele Dialekte.", "In Austria people speak many dialects."],
    ["Ich fühle mich hier inzwischen zu Hause.", "By now I feel at home here."],
  ],
};

export const THEMES5 = {
  "feste-feiertage": FESTE,
  umwelt: UMWELT,
  "geld-preise": GELD,
  "heimat-herkunft": HEIMAT,
};
